/** Declaration file generated by dts-gen */

export = tim_util;

declare const tim_util: {
    default: {
        createCustomMsg: any;
        createMsg: any;
        createTextMsg: any;
        getGroupFile: any;
        init: any;
        joinGroup: any;
        like: any;
        login: any;
        sendMsg: any;
        setEleVisible: any;
        setPosterShowStatus: any;
    };
};

